"""add_obligation_snooze_until

Revision ID: 45e14344f1ad
Revises: e009993a8b56
Create Date: 2026-05-09 19:35:05.318832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '45e14344f1ad'
down_revision: Union[str, None] = 'e009993a8b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obligations', sa.Column('snooze_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('obligations', 'snooze_until')
    # ### end Alembic commands ###
