"""add timeline cache to contracts

Revision ID: 76385c8f8053
Revises: bb65a635d774
Create Date: 2026-04-28 17:10:48.005545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '76385c8f8053'
down_revision: Union[str, None] = 'bb65a635d774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('timeline_events', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'timeline_events')
    # ### end Alembic commands ###
