"""add_user_management_tables

Revision ID: 88f63bfcf466
Revises: 76385c8f8053
Create Date: 2026-05-06 17:29:35.564049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '88f63bfcf466'
down_revision: Union[str, None] = '76385c8f8053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_invitations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('token', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('invited_by', sa.Uuid(), nullable=True),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_invitations_email'), 'org_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_org_invitations_org_id'), 'org_invitations', ['org_id'], unique=False)
    op.create_index(op.f('ix_org_invitations_token'), 'org_invitations', ['token'], unique=True)
    op.add_column('org_memberships', sa.Column('status', sa.String(length=32), nullable=False, server_default='active'))
    op.add_column('users', sa.Column('status', sa.String(length=32), nullable=False, server_default='active'))
    op.add_column('users', sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_active_at')
    op.drop_column('users', 'status')
    op.drop_column('org_memberships', 'status')
    op.drop_index(op.f('ix_org_invitations_token'), table_name='org_invitations')
    op.drop_index(op.f('ix_org_invitations_org_id'), table_name='org_invitations')
    op.drop_index(op.f('ix_org_invitations_email'), table_name='org_invitations')
    op.drop_table('org_invitations')
    # ### end Alembic commands ###
