"""add_obligations_table

Revision ID: ac6373a1598a
Revises: 88f63bfcf466
Create Date: 2026-05-07 19:52:03.486983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ac6373a1598a'
down_revision: Union[str, None] = '88f63bfcf466'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obligations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('extracted_by', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('responsible_party', sa.String(length=256), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('recurrence', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('section', sa.String(length=256), nullable=True),
    sa.Column('source_clause', sa.Text(), nullable=True),
    sa.Column('contract_name', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['extracted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obligations_contract_id'), 'obligations', ['contract_id'], unique=False)
    op.create_index(op.f('ix_obligations_org_id'), 'obligations', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_obligations_org_id'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_contract_id'), table_name='obligations')
    op.drop_table('obligations')
    # ### end Alembic commands ###
