"""add_contract_full_text

Revision ID: e009993a8b56
Revises: f2402dc26296
Create Date: 2026-05-09 16:32:45.506941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e009993a8b56'
down_revision: Union[str, None] = 'f2402dc26296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('full_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'full_text')
    # ### end Alembic commands ###
