"""add_obligation_reminders

Revision ID: f2402dc26296
Revises: ac6373a1598a
Create Date: 2026-05-08 11:37:46.814925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f2402dc26296'
down_revision: Union[str, None] = 'ac6373a1598a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obligations', sa.Column('reminder_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('obligations', sa.Column('reminder_email', sa.String(length=320), nullable=True))
    op.add_column('obligations', sa.Column('reminder_sent', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('obligations', 'reminder_sent')
    op.drop_column('obligations', 'reminder_email')
    op.drop_column('obligations', 'reminder_date')
    # ### end Alembic commands ###
